### ISSUE TITLE
QGIS 3 - plugin not available

### ISSUE THREAD

**Issue by crpage** [mattkernow/ZoomToPostcode-QGIS-Plugin#2]
I notice that this is not available in QGIS 3 (using 3.2), any chance of fixing as very useful

**Comment by sb2259** [comment]
I was also missing this excellent plugin on QGIS 3.  The attached version has been tested on QGIS 3.2 (both standard and OSGeo installations) on Windows 10.  It hasn't been tested with any other versions of QGIS or Windows.

[ZoomToPostcode.zip](https://github.com/mattkernow/ZoomToPostcode-QGIS-Plugin/files/2336837/ZoomToPostcode.zip)

**Comment by mattkernow** [comment]
Apologies for the slow reply. I have upgraded the plugin for QGIS3 and will update the official repository soon. Thanks for the offer though.

**Comment by mattkernow** [comment]
@crpage I have updated the plugin for qgis3. The changes are on the master branch. If you are able to test, it would be appreciated.
